accounts/urls.py
from django.urls import path

from .views import UserRegistrationView, LogoutView, UserLoginView


app_name = 'accounts'

urlpatterns = [
    path(
        "login/", UserLoginView.as_view(),
        name="user_login"
    ),
    path(
        "logout/", LogoutView.as_view(),
        name="user_logout"
    ),
    path(
        "register/", UserRegistrationView.as_view(),
        name="user_registration"
    ),
]

banking_system/urls.py
from django.contrib import admin
from django.urls import include, path

from core.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path(
        'transactions/',
        include('transactions.urls', namespace='transactions')
    )
]

transactions/urls.py
from django.urls import path
from . import views
from .views import DepositMoneyView, WithdrawMoneyView, TransactionRepostView,LoanCreationView,LoanRepostView,TransactionHomeView


app_name = 'transactions'


urlpatterns = [
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("home/", TransactionHomeView.as_view(), name="transaction_home"),
    path("report/", TransactionRepostView.as_view(), name="transaction_report"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),
    path("loanCreation/", LoanCreationView.as_view(), name="loan_creation"),
    path("loanreport/", LoanRepostView.as_view(), name="loan_report"),
    
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'core/index.html'

templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Dummy Banking System" />
        
        <title>
            {% block head_title %}Online Banking System{% endblock %}
        </title>
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

        {% block head_extra %}{% endblock %}
        <style>
            html,
            body {
                height: 100%;
                width: 100%;
            }
            
            body{
                /* background-image: url('{% static "img/logo.jpg" %}'); */
                background-repeat: no-repeat;
                background-size: contain;
                background-size: 48%;
                background-position: left;
                padding-bottom: 5em;
            }
            body #main{
                padding-bottom: 5em;
            }
            
            footer {
                position: fixed !important;
                bottom: 0 !important;
                width: 100%;
            }
        </style>
    </head>
    <body class="bg-gray-100">
        {% block body %}
            {% include 'core/navbar.html' %}
            <div class="lg:container lg:mx-auto" id="main">
                {% include 'core/messages.html' %}
                {% block content %}
                <!-- Add content here -->
                {% endblock %}
            </div>
           
            {% include 'core/footer.html' %}
            <div style="margin-bottom: 100px" >&nbsp;&nbsp;   </div>
        {% endblock %}
        {% block footer_extra %}{% endblock %}
    </body>

</html>

templates/core/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Dummy Banking System" />
        
        <title>
            {% block head_title %}Online Banking System{% endblock %}
        </title>
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

        {% block head_extra %}{% endblock %}
        <style>
            html,
            body {
                height: 100%;
                width: 100%;
            }
            
            body{
                background-image: url('{% static "img/logo.jpg" %}');
                background-repeat: no-repeat;
                background-size: contain;
                background-size: 48%;
                background-position: left;
                padding-bottom: 5em;
            }
            body #main{
                padding-bottom: 5em;
            }
            
            footer {
                position: fixed !important;
                bottom: 0 !important;
                width: 100%;
            }
        </style>
    </head>
    <body class="bg-gray-100">
        {% block body %}
            {% include 'core/navbar.html' %}
            <div class="lg:container lg:mx-auto" id="main">
                {% include 'core/messages.html' %}
                {% block content %}
                <!-- Add content here -->
                {% endblock %}
            </div>
            {% include 'core/footer.html' %}

        {% endblock %}
        {% block footer_extra %}{% endblock %}
    </body>

</html>

templates/core/footer.html
<footer class="footer bg-gradient-to-r from-blue-400 to-purple-500 p-2 px-10 pt-1 border-b-2 mt-10">
    <div class="container mx-auto px-6">
        <div class="mt-5 flex flex-col items-center">
            <div class="sm:w-2/3 text-center py-0 pb-2">
                <p class="text-md text-white font-bold mb-2">
                    © {% now "Y" %} Designed by Sandeep
                </p>
            </div>
        </div>
    </div>
</footer>

templates/core/index.html
{% extends 'core/base1.html' %} 
{% load static %}

{% block head_title %}Online Banking System{% endblock %} 

{% block content %}
<div class="container mx-auto flex flex-col md:flex-row items-center ">
  <div class="w-full lg:w-1/2 lg:py-6 text-center">
    <!-- You can add some content here if needed -->
  </div>
  <div class="flex flex-col w-full lg:w-1/2 justify-center items-start pt-6 pb-24 px-10 bg-blue-800 rounded-2xl bg-opacity-70">
    <h3 class="text-4xl font-bold text-white mb-8">
      At Online Banking System we believe that:
    </h3>
    <ul class="text-xl text-white list-disc mb-12">
      <li>“Good banking is produced not by good laws, but by good bankers.”</li>
      <li>“In banking or finance, trust is the only thing you have to sell.”</li>
    </ul>
    <a href="{% url 'accounts:user_registration' %}" class="bg-white text-blue-900 font-bold py-3 px-8 rounded-full hover:bg-blue-900 hover:text-white shadow-lg transition duration-300">
      Register to Open A New Account
    </a>
  </div>
</div>
{% endblock %}

templates/core/messages.html
{% for message in messages %}
<div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md mt-2" role="alert">
    <div class="flex">
        <div class="py-1"><svg class="fill-current h-6 w-6 text-teal-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/></svg></div>
        <div>
            <p class="font-bold">Success!</p>
            <p class="text-sm">{{ message }}</p>
        </div>
    </div>
</div>
{% endfor %}

templates/core/navbar.html
<nav class="flex items-center justify-between flex-wrap bg-gradient-to-r from-blue-400 to-purple-500  p-6 px-6" style="margin-top: -50px" >
    <div class="flex items-center flex-shrink-0 text-white mr-6">
        <a href="{% url 'home' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
            <style>
                body {
                    text-align: left;
                    margin-top: 30px;
                    color: #008080;
                }
                
                .font-bold {
                    font-weight: bolder;
                    
                }
                
                .text-xl {
                    font-size: 1.25rem;
                }
                
                .tracking-tight {
                    letter-spacing: -0.025em;
                }
                
                .text-orange-500 {
                    color: hwb(152 0% 0%);
                }
            </style>
            
            <span class="font-bold font-serif text-3xl "><span class="text-orange-500">Online Banking System</span></span>
            

        </a>
    </div>
    
    <div class="block lg:hidden">
        <button class="flex items-center px-3 py-2 border rounded text-white border-white-400 hover:text-white hover:border-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
    </div>
    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto px-10">
        {% if request.user.is_authenticated %}
            <div class="text-md lg:flex-grow">
                <a href="{% url 'transactions:transaction_home' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    
                    Home
                </a>
                <a href="{% url 'transactions:transaction_report' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Transactions
                </a>
                <a href="{% url 'transactions:deposit_money' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Deposit
                </a>
                <a href="{% url 'transactions:withdraw_money' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Withdraw
                </a>
                <a href="{% url 'transactions:loan_creation' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Apply Loan
                </a>
                <a href="{% url 'transactions:loan_report' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Applied Loans
                </a>
            </div>
            <div class="flex items-center justify-center lg:justify-end w-full lg:w-auto">
                <div class="text-blue-900 my-auto font-black px-5">Welcome, {{ request.user.first_name }} {{ request.user.last_name }} 🙂</div>
                <div class="text-blue-900 my-auto font-black px-5">Account No. {{request.user.account}}
                <a href="{% url 'accounts:user_logout' %}" class="bg-white text-gray-800 font-bold py-2 px-4 rounded ml-4 hover:bg-gray-300">Logout</a>
            </div>
        {% else %}
            <div class="text-md lg:flex-grow"></div>
            <div class="flex items-center justify-center lg:justify-end w-full lg:w-auto">
                <a href="{% url 'accounts:user_registration' %}" class="bg-white text-gray-800 font-bold py-2 px-4 rounded ml-4 hover:bg-gray-300">Register</a>
                <a href="{% url 'accounts:user_login' %}" class="bg-blue-900 text-white font-bold py-2 px-4 rounded ml-4 hover:bg-blue-800">Login</a>
            </div>
        {% endif %}
    </div>
</nav

 