accounts/urls.py
from django.urls import path

from .views import UserRegistrationView, LogoutView, UserLoginView


app_name = 'accounts'

urlpatterns = [
    path(
        "login/", UserLoginView.as_view(),
        name="user_login"
    ),
    path(
        "logout/", LogoutView.as_view(),
        name="user_logout"
    ),
    path(
        "register/", UserRegistrationView.as_view(),
        name="user_registration"
    ),
]

banking_system/urls.py
from django.contrib import admin
from django.urls import include, path

from core.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path(
        'transactions/',
        include('transactions.urls', namespace='transactions')
    )
]

transactions/urls.py
from django.urls import path
from . import views
from .views import DepositMoneyView, WithdrawMoneyView, TransactionRepostView,LoanCreationView,LoanRepostView,TransactionHomeView


app_name = 'transactions'


urlpatterns = [
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("home/", TransactionHomeView.as_view(), name="transaction_home"),
    path("report/", TransactionRepostView.as_view(), name="transaction_report"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),
    path("loanCreation/", LoanCreationView.as_view(), name="loan_creation"),
    path("loanreport/", LoanRepostView.as_view(), name="loan_report"),
    
]

transactions/models.py
from django.db import models

from .constants import TRANSACTION_TYPE_CHOICES
from accounts.models import UserBankAccount,User


class Transaction(models.Model):
    account = models.ForeignKey(
        UserBankAccount,
        related_name='transactions',
        on_delete=models.CASCADE,
    )
    amount = models.DecimalField(
        decimal_places=2,
        max_digits=12
    )
    balance_after_transaction = models.DecimalField(
        decimal_places=2,
        max_digits=12
    )
    transaction_type = models.PositiveSmallIntegerField(
        choices=TRANSACTION_TYPE_CHOICES
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.account.account_no)

    class Meta:
        ordering = ['timestamp']


class Loan(models.Model):
    user = models.ForeignKey(
        User,
        related_name='Loan',
        on_delete=models.CASCADE,
    )

    full_Name = models.CharField(max_length=512)
    email = models.CharField(max_length=512)
    birth_date = models.DateTimeField()
    loan_amount = models.CharField(max_length=512)
    loan_purpose =models.CharField(max_length=512)
    loan_emi = models.CharField(max_length=512)
    apply_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id)
        # .user.email

transactions/forms.py
import datetime

from django import forms
from django.conf import settings

from .models import Transaction,Loan
from .constants import LOAN_PURPOSE,LOAN_EMI


class TransactionForm(forms.ModelForm):

    class Meta:
        model = Transaction
        fields = [
            'amount',
            'transaction_type'
        ]

    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args, **kwargs)

        self.fields['transaction_type'].disabled = True
        self.fields['transaction_type'].widget = forms.HiddenInput()

    def save(self, commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance
        return super().save()


class DepositForm(TransactionForm):

    def clean_amount(self):
        min_deposit_amount = settings.MINIMUM_DEPOSIT_AMOUNT
        amount = self.cleaned_data.get('amount')

        if amount < min_deposit_amount:
            raise forms.ValidationError(
                f'You need to deposit at least {min_deposit_amount} $'
            )

        return amount


class WithdrawForm(TransactionForm):

    def clean_amount(self):
        account = self.account
        min_withdraw_amount = settings.MINIMUM_WITHDRAWAL_AMOUNT
        max_withdraw_amount = (
            account.account_type.maximum_withdrawal_amount
        )
        balance = account.balance

        amount = self.cleaned_data.get('amount')

        if amount < min_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at least {min_withdraw_amount} $'
            )

        if amount > max_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at most {max_withdraw_amount} $'
            )

        if amount > balance:
            raise forms.ValidationError(
                f'You have {balance} $ in your account. '
                'You can not withdraw more than your account balance'
            )

        return amount


class TransactionDateRangeForm(forms.Form):
    daterange = forms.CharField(required=False)

    def clean_daterange(self):
        daterange = self.cleaned_data.get("daterange")
        print(daterange)

        try:
            daterange = daterange.split(' - ')
            print(daterange)
            if len(daterange) == 2:
                for date in daterange:
                    datetime.datetime.strptime(date, '%Y-%m-%d')
                return daterange
            else:
                raise forms.ValidationError("Please select a date range.")
        except (ValueError, AttributeError):
            raise forms.ValidationError("Invalid date range")

class UserLoanCreation(forms.Form):
    full_Name = forms.CharField(widget=forms.TextInput(attrs={'autofocus':'on'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'autofocus':'off'}))
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    loan_amount = forms.CharField(widget=forms.TextInput(attrs={'autofocus':'off'}))
    loan_purpose = forms.ChoiceField(choices=LOAN_PURPOSE)
    loan_emi = forms.ChoiceField(choices=LOAN_EMI)

    class Meta:
        model = Loan
        fields = [
            'first_name',
            'email',
            'birth_date',
            'loan_amount',
            'loan_purpose',
            'loan_emi',
        ]


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'appearance-none block w-full bg-gray-200 '
                    'text-gray-700 border border-gray-200 rounded '
                    'py-3 px-4 leading-tight focus:outline-none '
                    'focus:bg-white focus:border-gray-500'
                )
            })

transactions/views.py
from dateutil.relativedelta import relativedelta
from django.shortcuts import HttpResponseRedirect, render
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, ListView,TemplateView,RedirectView

from transactions.constants import DEPOSIT, WITHDRAWAL
from transactions.forms import (
    DepositForm,
    TransactionDateRangeForm,
    WithdrawForm,UserLoanCreation
)
from transactions.models import Transaction, Loan

class TransactionRepostView(LoginRequiredMixin, ListView):
    template_name = 'transactions/transaction_report.html'
    model = Transaction
    form_data = {}

    def get(self, request, *args, **kwargs):
        form = TransactionDateRangeForm(request.GET or None)
        if form.is_valid():
            self.form_data = form.cleaned_data

        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset().filter(
            account=self.request.user.account
        )

        daterange = self.form_data.get("daterange")

        if daterange:
            queryset = queryset.filter(timestamp__date__range=daterange)

        return queryset.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'account': self.request.user.account,
            'form': TransactionDateRangeForm(self.request.GET or None)
        })

        return context

class TransactionHomeView(LoginRequiredMixin, ListView):
    template_name = 'transactions/transaction_home.html'
    model = Transaction
    form_data = {}

    def get(self, request, *args, **kwargs):
        form = TransactionDateRangeForm(request.GET or None)
        if form.is_valid():
            self.form_data = form.cleaned_data

        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset().filter(
            account=self.request.user.account
        )

        daterange = self.form_data.get("daterange")

        if daterange:
            queryset = queryset.filter(timestamp__date__range=daterange)

        return queryset.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'account': self.request.user.account,
            'form': TransactionDateRangeForm(self.request.GET or None)
        })

        return context

class LoanRepostView(LoginRequiredMixin, ListView):
    template_name = 'loans/loan_report.html'
    model = Loan
    form_data = {}


    def get_queryset(self):
        queryset = super().get_queryset().filter(
            user=self.request.user
        )

        # daterange = self.form_data.get("daterange")

        # if daterange:
        #     queryset = queryset.filter(timestamp__date__range=daterange)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


class TransactionCreateMixin(LoginRequiredMixin, CreateView):
    template_name = 'transactions/transaction_form.html'
    model = Transaction
    title = ''
    success_url = reverse_lazy('transactions:transaction_report')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'account': self.request.user.account
        })
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': self.title
        })

        return context


class DepositMoneyView(TransactionCreateMixin):
    form_class = DepositForm
    title = 'Deposit Money to Your Account'

    def get_initial(self):
        initial = {'transaction_type': DEPOSIT}
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account

        if not account.initial_deposit_date:
            now = timezone.now()
            next_interest_month = int(
                12 / account.account_type.interest_calculation_per_year
            )
            account.initial_deposit_date = now
            account.interest_start_date = (
                now + relativedelta(
                    months=+next_interest_month
                )
            )

        account.balance += amount
        account.save(
            update_fields=[
                'initial_deposit_date',
                'balance',
                'interest_start_date'
            ]
        )

        messages.success(
            self.request,
            f'{"{:,.2f}".format(float(amount))}$ was deposited to your account successfully'
        )

        return super().form_valid(form)


class WithdrawMoneyView(TransactionCreateMixin):
    form_class = WithdrawForm
    title = 'Withdraw Money from Your Account'

    def get_initial(self):
        initial = {'transaction_type': WITHDRAWAL}
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')

        self.request.user.account.balance -= form.cleaned_data.get('amount')
        self.request.user.account.save(update_fields=['balance'])

        messages.success(
            self.request,
            f'Successfully withdrawn {"{:,.2f}".format(float(amount))}$ from your account'
        )

        return super().form_valid(form)
        
class loadloantemplate(TemplateView):
     template_name = 'loans/loanCreation.html'
     model= Loan

     def post(self, request, *args, **kwargs):
        loan_form = UserLoanCreation(self.request.POST)
        print("hello",self.request.POST.get('full_Name'))
        l = Loan(user = request.user, full_Name=self.request.POST.get('full_Name'),email=self.request.POST.get('email'),birth_date=self.request.POST.get('birth_date'),loan_amount=self.request.POST.get('loan_amount'),loan_purpose=self.request.POST.get('loan_purpose'),loan_emi=self.request.POST.get('loan_emi'))
        l.save()

        if loan_form.is_valid():

            # user = loan_form.save()
    

            messages.success(
                self.request,
                (
                    # f'Thank You For Creating A Bank Account in Online Banking System. '
                    f'"Thank you for submitting your loan application. We have received your request and our team will review it as soon as possible. You can expect to hear back from us within the next few business days regarding the status of your application. If we require any additional information, we will contact you directly. Thank you for choosing our banking services."'
                )
            )
        

        return self.render_to_response(
            self.get_context_data(
                loan_form=loan_form,
            )
        )

     def get_context_data(self, **kwargs):
        if 'loan_form' not in kwargs:
            kwargs['loan_form'] = UserLoanCreation()
        

        return super().get_context_data(**kwargs)



class LoanCreationView(loadloantemplate):

    def loanCreation():
        return

   

templates/transactions/transaction_form.html
{% extends 'core/base.html' %} {% block head_title %}{{ title }}{% endblock %} {% block content %}

<div class="w-full flex mt-5 justify-center" style="padding-right: 50px;">
    <div class="bg-white w-5/12">
        <h1 class="font-serif font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
        <hr />
        <form method="post" class="px-8 pt-6 pb-8 mb-4">
            {% csrf_token %}

            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                    Amount
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount">
            </div>
            {% if form.amount.errors %} {% for error in form.amount.errors %}
            <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
            {% endfor %} {% endif %}
            <div class="flex w-full justify-center">
                <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2" type="submit">
                Submit
            </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/transactions/transaction_home.html
{% extends 'core/base.html' %} {% load humanize %} {% block head_title %}Transaction Report{% endblock %} {% block head_extra %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" /> {% endblock %} {% block content %}
<div class="my-3 py-3 px-4 bg-white rounded-xl shadow-md">
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-2">Welcome, {{ request.user.first_name }} {{ request.user.last_name }} 🙂</h1>
    
    <div class="text-blue-900 my-auto font-black px-5 text-center">Account No. {{request.user.account}}

    </div>
    <div class="justify-center">
        <h1 class="text-center">Current Available Balance  $ {{ account.balance|floatformat:2|intcomma }}</h1>  
        <!-- <h1></h1> -->

  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto px-10 justify-center" style="margin-top: 10px"  >
    <div class="flex items-center justify-between mr-4" href="{% url 'transactions:withdraw_money' %}">
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
            <a href="{% url 'transactions:deposit_money' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                Deposit
            </a>
        </button>
    </div>
      
                   <div class="flex items-center justify-between mr-4" href="{% url 'transactions:withdraw_money' %}">
                    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                        <a href="{% url 'transactions:withdraw_money' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                            Withdraw
                        </a>
                    </button>
                </div>

  </div>
    </div>
    <!-- <h1 class="font-serif font-bold text-3xl text-center pb-3 pt-2">Transaction Report</h1>
    <hr />
    <form method="get" id="filter">
        <div class="flex justify-center">
            <div class="mt-6 h-8 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative  w-4/12">
                <input type="search" name="daterange" id="search" placeholder="Filter using date range" class="appearance-none w-full outline-none focus:outline-none active:outline-none" autocomplete="off" value="{{ request.GET.daterange}}" />
                <button type="submit" class="ml-1 outline-none focus:outline-none active:outline-none">
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="w-6 h-6">
                        <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                    </svg>
                </button>
            </div>
        </div>
        {% if form.daterange.errors %} {% for error in form.daterange.errors %}
        <p class="text-red-600 text-sm italic">{{ error }}</p>
        {% endfor %} {% endif %}
    </form>
    <table class="table-auto mx-auto w-full mt-13 border-collapse">
        <thead class="bg-gray-800 text-white">
            <tr class="uppercase font-semibold text-sm">
                <th class=" border border-black px-4 py-2">Date</th>
                <th class=" border border-black px-4 py-2">Transaction Type</th>
                <th class=" border border-black px-4 py-2">Amount</th>
                <th class=" border border-black px-4 py-2">Balance After Transaction</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in object_list %}
            <tr class="{% cycle 'bg-gray-300' 'bg-white-100' %}">
                <td class="border border-blue-900 px-4 py-2">{{ transaction.timestamp|date:"F d, Y h:i A" }}</td>
                <td class="border border-blue-900 px-4 py-2">{{ transaction.get_transaction_type_display }}</td>
                <td class="border border-blue-900 px-4 py-2 text-right">$ {{ transaction.amount|floatformat:2|intcomma }}</td>
                <td class="border border-blue-900 px-4 py-2 text-right">$ {{ transaction.balance_after_transaction|floatformat:2|intcomma }}</td>
            </tr>
            {% endfor %}
            <tr class="bg-gray-600 text-white">
                <th class="border border-blue-900 px-4 py-2 text-right" colspan="3">Current Balance</th>
                <th class="border border-blue-900 px-4 py-2 text-right">$ {{ account.balance|floatformat:2|intcomma }}</th>
            </tr>
        </tbody>
    </table> -->
</div>
{% endblock %} {% block footer_extra %}
<script type="text/javascript">
    var def_date = '{{request.GET.daterange}}'
    def_date = def_date == "" ? moment().format("Y-MM-DD") + " - " + moment().format("Y-MM-DD") : def_date
    var date_split = def_date.split(" - ")
    var start_date = moment(date_split[0]).format("MM/DD/Y")
    var end_date = moment(date_split[1]).format("MM/DD/Y")
    console.log(start_date, end_date)
    $(function() {
        $('input[name="daterange"]').daterangepicker({
            autoUpdateInput: false,
            startDate: start_date,
            endDate: end_date,
            locale: {
                cancelLabel: "Clear",
            },
        });

        $('input[name="daterange"]').on("apply.daterangepicker", function(ev, picker) {
            $(this).val(picker.startDate.format("YYYY-MM-DD") + " - " + picker.endDate.format("YYYY-MM-DD"));
            $('#filter').submit()
        });

        $('input[name="daterange"]').on("cancel.daterangepicker", function(ev, picker) {
            $(this).val("");
            $('#filter').submit()
        });
    });
</script>
{% endblock %}

templates/transactions/transaction_report.html
{% extends 'core/base.html' %} {% load humanize %} {% block head_title %}Transaction Report{% endblock %} {% block head_extra %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" /> {% endblock %} {% block content %}
<div class="my-3 py-3 px-4 bg-white rounded-xl shadow-md">
    <h1 class="font-serif font-bold text-3xl text-center pb-3 pt-2">Transaction Report</h1>
    <hr />
    <form method="get" id="filter" style="margin-bottom: 10px" >
        <div class="flex justify-center">
            <div class="mt-6 h-8 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative  w-4/12">
                <input type="search" name="daterange" id="search" placeholder="Filter using date range" class="appearance-none w-full outline-none focus:outline-none active:outline-none" autocomplete="off" value="{{ request.GET.daterange}}" />
                <button type="submit" class="ml-1 outline-none focus:outline-none active:outline-none">
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="w-6 h-6">
                        <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                    </svg>
                </button>
            </div>
        </div>
        {% if form.daterange.errors %} {% for error in form.daterange.errors %}
        <p class="text-red-600 text-sm italic">{{ error }}</p>
        {% endfor %} {% endif %}
    </form>
    <table class="table-auto mx-auto w-full mt-13 border-collapse">
        <thead class="bg-gray-800 text-white">
            <tr class="uppercase font-semibold text-sm">
                <th class=" border border-black px-4 py-2">Date</th>
                <th class=" border border-black px-4 py-2">Transaction Type</th>
                <th class=" border border-black px-4 py-2">Amount</th>
                <th class=" border border-black px-4 py-2">Balance After Transaction</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in object_list %}
            <tr class="{% cycle 'bg-gray-300' 'bg-white-100' %}">
                <td class="border border-blue-900 px-4 py-2">{{ transaction.timestamp|date:"F d, Y h:i A" }}</td>
                <td class="border border-blue-900 px-4 py-2">{{ transaction.get_transaction_type_display }}</td>
                <td class="border border-blue-900 px-4 py-2 text-right">$ {{ transaction.amount|floatformat:2|intcomma }}</td>
                <td class="border border-blue-900 px-4 py-2 text-right">$ {{ transaction.balance_after_transaction|floatformat:2|intcomma }}</td>
            </tr>
            {% endfor %}
            <tr class="bg-gray-600 text-white">
                <th class="border border-blue-900 px-4 py-2 text-right" colspan="3">Current Balance</th>
                <th class="border border-blue-900 px-4 py-2 text-right">$ {{ account.balance|floatformat:2|intcomma }}</th>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %} {% block footer_extra %}
<script type="text/javascript">
    var def_date = '{{request.GET.daterange}}'
    def_date = def_date == "" ? moment().format("Y-MM-DD") + " - " + moment().format("Y-MM-DD") : def_date
    var date_split = def_date.split(" - ")
    var start_date = moment(date_split[0]).format("MM/DD/Y")
    var end_date = moment(date_split[1]).format("MM/DD/Y")
    console.log(start_date, end_date)
    $(function() {
        $('input[name="daterange"]').daterangepicker({
            autoUpdateInput: false,
            startDate: start_date,
            endDate: end_date,
            locale: {
                cancelLabel: "Clear",
            },
        });

        $('input[name="daterange"]').on("apply.daterangepicker", function(ev, picker) {
            $(this).val(picker.startDate.format("YYYY-MM-DD") + " - " + picker.endDate.format("YYYY-MM-DD"));
            $('#filter').submit()
        });

        $('input[name="daterange"]').on("cancel.daterangepicker", function(ev, picker) {
            $(this).val("");
            $('#filter').submit()
        });
    });
</script>
{% endblock %}